@AuthService.API_HostAddress = https://localhost:7088/api

POST {{AuthService.API_HostAddress}}/auth/Login
Accept: application/json
Content-Type: application/json
{
  "email": "user@gmail.com",
  "password": "User@12345678"
}
###
